import type { Metadata } from "next";

import "@/app/globals.css";
import Navbar from "@/components/ui/Navbar";
import PromoModal from "@/components/ui/PromoModal";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="relative antialiased overflow-x-hidden overflow-y-auto max-w-full">
        <PromoModal />
        <Navbar />
        <main>{children}</main>
        <footer className="flex p-16 items-center justify-center text-center text-neutral-400">
          © {new Date().getFullYear()} GOLD COAST MORIB INTERNATIONAL RESORT
        </footer>
      </body>
    </html>
  );
}
